Settings:
  Prefix: '#00F7FB&lSupply Drop &8➟ ' # The prefix before the messages CrazyEnvoys sends.
  Toggle-Metrics: true # Turn on and off if your server stats are sent to https://bstats.org/ - Requires a restart!
  Falling-Block-Toggle: true # Toggle if it spawns a falling block or if the crates just appear.
  Falling-Block: '138' # The block that will be falling.
  Fall-Height: 15 # How high the falling blocks spawn.
  # This option should ONLY be used if Random-Locations is false.
  Max-Crate-Toggle: true # If true then only a specified amount of crates will spawn and if false then all crates will spawn.
  Random-Amount: true # Selects a random number of crates between the Min-Crates and Max-Crates value (if true)
  Min-Crates: 15 # The min amount of crates that will spawn.
  Max-Crates: 27 # The max amount of crates that will spawn.
  Random-Locations: false # If true you will need to make sure to set the center location.
  Max-Radius: 300 # The maximum distance the crates will fall from the center.
  Min-Radius: 20 # The minimum distance from the middle the crates will fall from.
  Envoy-Run-Time: 5m # The amount of time the crazyenvoy event will go for.
  Envoy-Timer-Toggle: true # If the crazyenvoys happen on an interval. If false the only wait it will start is if it's started with the command or flare.
  Envoy-Cooldown-Toggle: true # Toggle if it uses a cooldown or a specified time of the day.
  Envoy-Filter-Players-Zero: true # Toggle if you want CrazyEnvoys to ignore when player counts are 0.
  Envoy-Cooldown: 2h # The time till the crazyenvoy event will happen again.
  Envoy-Time: 2:00 AM # A specified time of the day that an envoy will happen. Please use 1-12 for hours and 0-59 for minutes.
  Minimum-Players-Toggle: false # When the crazyenvoy is about to start toggle if there needs to be a minimum amount of players. (Does not affect flares)
  Minimum-Flare-Toggle: false # Toggle if using a flare has to meet the minimum players' requirement. Minimum-Players-Toggle must be true for this to work.
  Minimum-Players: 12 # The minimum amount of players needed to start the crazyenvoy.
  Broadcast-Crate-Pick-Up: true # Toggle if when a player gets a crate if it broadcasts the message.
  Crate-Collect-Cooldown: # If when a player collects a crate if they have to wait to collect another.
    Toggle: true # Toggle this option on and off.
    Time: 15s # The time till they have to wait.
  World-Messages:
    Toggle: false # Toggle if the broadcast messages are only in a specific worlds.
    Worlds: # The worlds you wish to have the messages only show up in.
      - world
  Envoy-Warnings: # The times that will make the warning messages.
    - 1h
    - 30m
    - 15m
    - 5m
    - 1m
    - 30s
    - 15s
    - 3s
    - 2s
    - 1s
  Flares: # Options about flares. Players need the crazyenvoy.flare.use permission to use the flares.
    Item: '76' # The time the flares are.
    Name: '&7&l(&4&l!&7&l) &cFlare' # The name of the flare.
    Lore: # The lore of the flare.
      - '&7Right click me to'
      - '&7start an crazyenvoy event.'
    World-Guard: # The options for when using world guard regions to make flares work only in those regions.
      Toggle: false # If they have to use flares in specified regions.
      Regions: # The name of the regions you can use flares in.
        - WarZone
  Crate-Countdown:
    Toggle: false
    Time: 120
    Message: '&cReady to claim.'
    Message-Seconds: ' seconds.'
