
locale:
  world-names:
    world: World
    world_nether: Nether
    world_the_end: The End

Entity:
  Effects:
    List:
      Bleed:
        Name: Bleed
        Description:
        - '&7You''re bleeding!'
        - '&7You''re losing &c%effect_bleed_damage% health'
        - '&7every &c%effect_interval% seconds&7.'
      Blind:
        Name: Blind
        Description:
        - '&7You''re blinded!'
        - '&7Your attacks are useless.'
      Disarm:
        Name: Disarm
        Description:
        - '&7You have been disarmed!'
      Dodge:
        Name: Dodge
        Description:
        - '&7You dodging next &f%effect_charges% &7attacks!'
      Resist:
        Name: Resist
        Description:
        - '&7You have a resistance for certain effects!'
      Root:
        Name: Root
        Description:
        - '&7Your movement is restricted!'
      Stun:
        Name: Stun
        Description:
        - '&7You can not move, attack and interact!'
    Boss_Bar:
      Enabled: true
      Duration_Format:
        Time: '&7%effect_duration%'
        Time_With_Charges: '&7%effect_duration% &8| &7x%effect_charges%'
        Charges: '&7x%effect_charges%'
      Positive:
        Color: BLUE
        Style: SOLID
        Title: '&9%effect_name% &8- %duration%'
      Negative:
        Color: RED
        Style: SOLID
        Title: '&c%effect_name% &8- %duration%'
Locale:
  World_Names:
    world: World
    world_nether: Nether
    world_the_end: The End
Plugin:
  Prefix: NexEngine
  Command_Aliases: nexengine
  Language: en
  Name: NexEngine
