messages:
  withdraw:
    message: '&#0EC1FF&lRussian Roulette &8&8➟ &7Congratulations, you have won &c${reward}!'
    sound:
      id: minecraft:block.note_block.bell

sounds:
  lost:
    id: minecraft:block.end_gateway.spawn
    volume: 1.0
    pitch: 1.0
  continue:
    id: minecraft:entity.experience_orb.pickup
    volume: 1.0
    pitch: 1.2

items:
  winItem:
    material: GOLD_INGOT
    name: '&a&lWIN!'
  lostItem:
    material: SKELETON_SKULL
    name: '&c&lLOST!'
  undecidedItem:
    material: TOTEM_OF_UNDYING
    name: '&ePick a totem!'

options:
  totems: 4
  maxBet: 500000
  multiplier: 2

addMenu:
  title: Russian Roulette (${amount})
  rows: 3
  filler:
    material: GRAY_STAINED_GLASS_PANE
    name: '&f'
    slots:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
  '1':
    material: PAPER
    name: '&a&l+500'
    money: 500
    slots:
    - 10
  '2':
    material: PAPER
    name: '&a&l+3,000'
    money: 3000
    slots:
    - 11
  '3':
    material: PAPER
    name: '&a&l+10,000'
    money: 10000
    slots:
    - 12
  '4':
    material: PAPER
    name: '&a&l+25,000'
    money: 25000
    slots:
    - 13
  '5':
    material: PAPER
    name: '&a&l+50,000'
    money: 50000
    slots:
    - 14
  '6':
    material: PAPER
    name: '&a&l+100,000'
    money: 100000
    slots:
    - 15
  '7':
    material: PAPER
    name: '&a&l+250,000'
    money: 250000
    slots:
    - 16

removeMenu:
  title: Russian Roulette (${amount})
  rows: 3
  filler:
    material: GRAY_STAINED_GLASS_PANE
    name: '&f'
    slots:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
  '1':
    material: PAPER
    name: '&c&l-500'
    money: 500
    slots:
    - 10
  '2':
    material: PAPER
    name: '&c&l-3,000'
    money: 3000
    slots:
    - 11
  '3':
    material: PAPER
    name: '&c&l-10,000'
    money: 10000
    slots:
    - 12
  '4':
    material: PAPER
    name: '&c&l-25,000'
    money: 25000
    slots:
    - 13
  '5':
    material: PAPER
    name: '&c&l-50,000'
    money: 50000
    slots:
    - 14
  '6':
    material: PAPER
    name: '&c&l-100,000'
    money: 100000
    slots:
    - 15
  '7':
    material: PAPER
    name: '&c&l-250,000'
    money: 250000
    slots:
    - 16

mainMenu:
  title: Russian Roulette
  rows: 3
  bulletSlots:
  - 10
  - 11
  - 12
  - 14
  - 15
  - 16
  fillerSlots:
    material: GRAY_STAINED_GLASS_PANE
    name: '&fPick a totem!'
    slots:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
  specialItems:
    deductFromBet:
      material: RED_DYE
      name: '&c&lDeduct from bet'
      lore:
      - '&f'
      - '&7Click to remove from your bet!'
      slots:
      - 3
    addToBet:
      material: LIME_DYE
      name: '&a&lAdd to bet'
      lore:
      - '&f'
      - '&7Click to add to your bet!'
      slots:
      - 5
    totalBet:
      material: DIAMOND
      name: '&b&lTotal bet'
      lore:
      - '&f'
      - '&7Your total bet'
      - '&7 ➟ &f${amount}'
      slots:
      - 4

loseMenu:
  title: Russian Roulette
  rows: 3
  fillerSlots:
    material: GRAY_STAINED_GLASS_PANE
    name: '&f'
    slots:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
  fillerSlots2:
    material: RED_STAINED_GLASS_PANE
    name: '&f'
    slots:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 17
    - 19
    - 21
    - 23
    - 25
  specialItems:
    totalBet:
      material: DIAMOND
      name: '&b&lTotal bet'
      lore:
      - '&f'
      - '&7Your total bet'
      - '&7 ➟ &f${amount}'
      slots:
      - 4
    reroll:
      material: GOLDEN_APPLE
      name: '&a&lReroll'
      lore:
      - '&f'
      - '&7Click to reroll!'
      slots:
      - 22

winMenu:
  title: Russian Roulette
  rows: 3
  fillerSlots:
    material: GRAY_STAINED_GLASS_PANE
    name: '&f'
    slots:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
  fillerSlots2:
    material: YELLOW_STAINED_GLASS_PANE
    name: '&f'
    slots:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 17
    - 19
    - 21
    - 23
    - 25
  specialItems:
    totalBet:
      material: DIAMOND
      name: '&b&lTotal bet'
      lore:
      - '&f'
      - '&7Your total bet'
      - '&7 ➟ &f${amount}'
      slots:
      - 4
    reroll:
      material: GOLDEN_APPLE
      name: '&a&lReroll'
      lore:
      - '&f'
      - '&7Click to reroll!'
      slots:
      - 22
