rank_vip:
  Name: '&d&nVIP Rank'
  Description:
  - '&7Example rank lore...'
  Price: 50
  Purchase_Cooldown: -1
  Priority: 10
  Inheritance:
    Rewards: []
    Price: []
  Preview:
    material: STONE_PICKAXE
    amount: 1
    durability: 0
    enchanted: false
    item-flags:
    - HIDE_ENCHANTS
    - HIDE_ATTRIBUTES
    - HIDE_UNBREAKABLE
    - HIDE_DESTROYS
    - HIDE_PLACED_ON
    - HIDE_POTION_EFFECTS
    - HIDE_DYE
    unbreakable: false
  Rewards:
    Commands:
    - '[CONSOLE] broadcast &f%player% &7just purchased the &dVIP Rank&7!'
    - '[CONSOLE] lp user %player% group parent set vip'
  Store:
    Slot: 11
    Page: 1

rank_vip_plus:
  Name: '&aVIP+ Rank'
  Description:
  - '&7Example rank lore...'
  Price: 150
  Purchase_Cooldown: -1
  Priority: 20
  Inheritance:
    Rewards: []
    Price:
    - rank_vip
  Preview:
    material: IRON_PICKAXE
    amount: 1
    durability: 0
    enchanted: false
    item-flags:
    - HIDE_ENCHANTS
    - HIDE_ATTRIBUTES
    - HIDE_UNBREAKABLE
    - HIDE_DESTROYS
    - HIDE_PLACED_ON
    - HIDE_POTION_EFFECTS
    - HIDE_DYE
    unbreakable: false
  Rewards:
    Commands:
    - '[CONSOLE] broadcast &f%player% &7just purchased the &aVIP+ Rank&7!'
    - '[CONSOLE] lp user %player% group parent set vip_plus'
  Store:
    Slot: 13
    Page: 1

rank_mvp:
  Name: '&bMVP Rank'
  Description:
  - '&7Example rank lore...'
  Price: 300
  Purchase_Cooldown: -1
  Priority: 30
  Inheritance:
    Rewards: []
    Price:
    - rank_vip
    - rank_vip_plus
  Preview:
    material: DIAMOND_PICKAXE
    amount: 1
    durability: 0
    enchanted: false
    item-flags:
    - HIDE_ENCHANTS
    - HIDE_ATTRIBUTES
    - HIDE_UNBREAKABLE
    - HIDE_DESTROYS
    - HIDE_PLACED_ON
    - HIDE_POTION_EFFECTS
    - HIDE_DYE
    unbreakable: false
  Rewards:
    Commands:
    - '[CONSOLE] broadcast &f%player% &7just purchased the &bMVP Rank&7!'
    - '[CONSOLE] lp user %player% group parent set mvp'
  Store:
    Slot: 15
    Page: 1
