###########################################################
#                                                         #
#   LockLogin source is a plugin under GSA GPL license    #
#             https://locklogin.eu/license                #
#                                                         #
#                                                         #
#                   For more help                         #
#             go to: https://rb.gy/simfd2                 #
#                                                         #
###########################################################

#This is used by 2fa
#and some plugin messages
ServerName: 'zktdnbxv'

#NOT IMPLEMENTED YET
#
# This is the KarmaAPI panel service. When enabled, the server
# won't store any account, instead, users will be authenticated and
# registered using the KarmaPanel ( https://karmadev.es | https://karmaconfigs.ml | https://karmarepo.ml ).
#
# ( IF ANY OF THE URLS WORK, TRY WITH https://backup.[karmadev.es|karmaconfigs.ml|karmarepo.ml] )
#
# By enabling this you accept that player accounts won't pertain to you so you won't
# be able to perform actions under them like requesting info about them. ( /playerinfo )
# or removing an account. If removing an account is what you want, the user must login in any
# of the URLs provided before and remove his account manually.
OnlineAccounts: true

#While true, if your server is in bungeecord
#mode. The server MOTD will be replaced with
#This server is being protected by LockLogin
#and/or while is being started, the motd will
#be replaced with:
#
#LockLogin | Starting server
BungeeMotd: false

#This is used by LockLogin panel to
#make sure the communication gets at least
#encrypted
PanelKey: ''

#Registration options
# Boss -> Shows a boss bar which health and color
#         depends on the remaining time ( bar color requires
#         MC 1.9+ )
# Blind -> Applies a blind potion
#          effect when the player
#          joins if he's not registered
#
# Nausea -> Applies a confusion effect
#           when the player joins if he's
#           not registered, util for anarchy
#           servers
#
# TimeOut -> The maximum time the player has
#            to perform the register
#
# Max -> The maximum amount of accounts allowed
#        TO REGISTER per IP
Register:
  Boss: true
  Blind: false
  Nausea: false
  TimeOut: 60
  Max: 2

#Login options
# Boss -> Shows a boss bar which health and color
#         depends on the remaining time ( bar color requires
#         MC 1.9+ )
# Blind -> Applies a blind potion
#          effect when the player
#          joins if he's not logged in
#
# Nausea -> Applies a confusion effect
#           when the player joins if he's
#           not logged in, util for anarchy
#           servers
#
# TimeOut -> The maximum time the player has
#            to perform the login
#
# MaxTries -> The maximum amount of password tries
#             the player has before getting kicked
Login:
  Boss: true
  Blind: true
  Nausea: true
  TimeOut: 30
  MaxTries: 5

#Toggle plugin sessions system.
#
# Time -> The time (in minutes) an account
#         will be valid ( 0 = 59 seconds )
#
#   The maximum amount of a session life
#   time is 30 minutes
#This requires the player to have a
#valid LockLogin pin configured, otherwise
#it won't work
Sessions:
  Enabled: false
  Time: 5

#Toggle plugin IP health check
# While enabled, the plugin will
# reject incoming connections of
# IPS with these conditions:
#
# - Is null or invalid
# - Is in the plugin's proxy list
# - Can't be resolved by the server
IpHealthCheck: true

#Validate UUIDs by generating them
#depending on the server context
#(online mode or offline mode)
#This prevents an attacker from joining
#with an spoofed UUID
UUIDValidator: true

#Hide non logged players from
#logged ones and logged players from
#non logged.
HideNonLogged: false

#Login/Register messages in chat
#interval, minimum is 5, maximum is
#the specified in Login/Register section
#( TimeOut time )
MessagesInterval:
  Registration: 5
  Logging: 5

#Captcha options
# Available options:
#
# Difficulty -> Captcha difficulty settings
#   Length -> Captcha code length ( min is 8, max is 16 )
#   Letters -> Include letters in the captcha
#   Strikethrough -> Strikethrough captcha settings
#     Enabled -> Enable strikethrough feature
#     Random -> Randomize the characters with strikethrough
#             effect
Captcha:
  Enabled: true
  Difficulty:
    Length: 8
    Letters: true
  Strikethrough:
    Enabled: true
    Random: true

#Encryption configuration
# Available types:
# "SHA512"
# "SHA256"
# "BCrypt"
# "Argon2i"
# "Argon2id"
# "AuthMeSHA"
#
# Encrypt: will encrypt the
# passwords in Base64
#
# VirtualID: Hash the password with a
# virtual ID to protect the player accounts
# to brute force attacks if your user database
# gets leaked
Encryption:
  Passwords: 'SHA512'
  Pins: 'SHA512'
  Encrypt: true
  VirtualID: false

#Block login/register attempt when the
#client has an insecure password, while
#login process, the player account will be
#unregistered ( only password ).
#
#While this in false, only a warning will be
#set to the client telling him his password
#is not safe
BlockUnsafePasswords: true

#BurteForce options
# Tries -> The maximum amount of tries
#          the IP has to login per connection
#          (Per connection = Respecting Login's MaxTries)
#
# BlockTime -> The time (in minutes) the IP will
#              be blocked if tries get to 0
BruteForce:
  Tries: 3
  BlockTime: 30

#AllowSameIP is a feature that will
#allow a player that is already connected
#to join the server if his IP is the same
#that the one is already connected.
#By enabling this the player will still have
#to login
AllowSameIp: true

#Enable pin feature (This is not 2FA)
#LockLogin pin or LockLogin Pinner is
#an extra pin feature that adds an extra
#security layer to your players accounts
Pin: true

#Enable 2FA feature (using Google Authenticator)
#This adds and extra security layer to your
#players account, but since due Spigot API is
#bypasseable, you should enable PIN feature
#For help while using/scanning 2FA QR codes
#check these video
#
#https://www.youtube.com/watch?v=zcLxFQgCrnU
2FA: true

#Updater options
# Channel -> Update system channel;
#            Available channels:
#            - RELEASE
#            - RC | RELEASECANDIDATE | RELEASE_CANDIDATE
#            - SNAPSHOT
#
# Check -> Enable the update checker
#          if disabled, an unique check
#          will be performed on each server
#          start
#
# CheckTime -> The time (in minutes) before each
#              update check, the minimum is 5 and
#              the maximum is 86400 (1 day)
Updater:
  Channel: 'RELEASE'
  Check: true
  CheckTime: 10

#Spawn options
# Manage -> Allow LockLogin to manage
#           on-join spawn. To set the
#           spawn you must use /setloginspawn
# TakeBack -> Teleport the player back to his
#             latest location after logging in
# SpawnDistance -> The minimum distance required
#                  from spawn to store the last
#                  player location
Spawn:
  Manage: false
  TakeBack: false
  SpawnDistance: 30

#Enable clear chat feature, this
#option will clear ONLY CONNECTED
#PLAYER chat, there won't be a change
#for other players
ClearChat: false

#Toggle LockLogin name verifier when
#a player joins the server, using
#mojang's name rules:
#4 chars min, 16 max, only "_" allowed
CheckNames: true

#Toggle LockLogin similar name checker.
#While this option is true, if a player
#called someone joins the server, another
#player won't be able to join as SomeOne,
#soMeoNe and so on until the original
#someone removes his account completely.
EnforceNameCheck: false

#Define the name check mode
#
# 1:
#   - The name contains letters and numbers
#   - The name is over 3 and under 16 characters
#   - Only _ as special character
#   - UTF-8 characters allowed
#
# 2:
#   - The name contains letters and numbers
#   - The name is over 3 and under 16 characters
#   - Only _ as special character
#   - UTF-8 characters not allowed ( only ASCII )
NameCheckProtocol: 2

#Plugin language
#
# Available languages are:
# English ( en_EN | English )
# Spanish ( es_ES | Spanish )
# French ( fr_FR | French )
# Simplified Chinese ( zh_CN | Chinese simplified | Simplified chinese )
# being english by default
Lang: 'en_EN'

#Module commands prefix
ModulePrefix: '$'
