aliases:
- trade+
trade-command-compatible-mode: false
excess-chest:
  enabled: true
  title: '&7Your inventory is full!'
trade-logs: false
allow-same-ip-trade: true
permissions:
  required: false
  send: tradeplus.send
  accept: tradeplus.accept
requestcooldownseconds: 20
allow-trade-in-creative: false
blocked:
  blacklist:
  - bedrock
  - shulker_box
  named-items: false
  lore:
  - EXAMPLE_BLOCKED_LORE
  regex: ''
action: ''
ranges:
  sameworld: 1.0E124
  crossworld: 0.0
  allowcrossworld: true
  blocked-worlds:
  - ThisWorldDoesntExistButItsBlocked
  - NeitherDoesThisOneButItIsToo
antiscam:
  countdown: 10
  cancelonchange: true
  preventchangeonaccept: true
  discrepancy-detection: true
end-display:
  enabled: true
  timer: 0
spectate:
  enabled: true
  broadcast: true
extras:
  type:
    prefix: '&b&lTrade &8➟ &r'
    empty: '&ePlease enter your %EXTRA% offer, or type ''cancel''.'
    valid: '&aClick output slot to submit offer.'
    invalid: '&cInvalid amount entered!'
    maximum: '&cYou have %BALANCE% %EXTRA%'
  economy:
    enabled: true
    name: money
    material: gold_ingot
    display: '&e&lYour Money Offer: &f%AMOUNT%'
    theirdisplay: '&e&lTheir Money Offer: &f%AMOUNT%'
    lore:
    - '&8❖&7 Click to edit your offer!'
    customModelData: 0
    increment: 10.0
    taxpercent: 0
    mode: chat
  experience:
    enabled: true
    name: experience points
    material: experience_bottle
    display: '&a&lYour XP Offer: &f%AMOUNT% &c&l(%LEVELS% Levels)'
    theirdisplay: '&a&lTheir XP Offer: &f%AMOUNT% &c&l(%LEVELS% Levels)'
    lore:
    - '&8❖&7 Click to edit your offer!'
    customModelData: 0
    increment: 5
    taxpercent: 0
    mode: chat
    levelMode: false
  playerpoints:
    enabled: false
    name: player points
    display: '&bYour PlayerPoints offer is &3%AMOUNT%'
    theirdisplay: '&bTheir PlayerPoints offer is &3%AMOUNT%'
    lore:
    - '&fClick to edit your offer!'
    - '&fYou have %BALANCE% player points.'
    customModelData: 0
    increment: 5
    taxpercent: 0
    mode: chat
  griefprevention:
    enabled: true
    name: claim blocks
    material: golden_shovel
    display: '&eYour GriefPrevention offer is &6%AMOUNT%'
    theirdisplay: '&eTheir GriefPrevention offer is &6%AMOUNT%'
    lore:
    - '&fClick to edit your offer!'
    - '&fYou have %BALANCE% protection blocks.'
    customModelData: 0
    increment: 1
    taxperecent: 0
    mode: chat
  enjinpoints:
    enabled: false
    name: enjin points
    material: emerald
    display: '&eYour EnjinPoints offer is &6%AMOUNT%'
    theirdisplay: '&eTheir EnjinPoints offer is &6%AMOUNT%'
    lore:
    - '&fClick to edit your offer!'
    - '&fYou have %BALANCE% enjin points.'
    customModelData: 0
    increment: 1
    taxpercent: 0
    mode: chat
  tokenenchant:
    enabled: true
    name: token enchant points
    material: enchanted_book
    display: '&eYour TokenEnchant tokens offer is &6%AMOUNT%'
    theirdisplay: '&eTheir TokenEnchants tokens offer is &6%AMOUNT%'
    lore:
    - '&fClick to edit your offer!'
    - '&fYou have %BALANCE% enchant tokens.'
    customModelData: 0
    increment: 1
    taxpercent: 0
    mode: chat
  tokenmanager:
    enabled: true
    name: tokens
    material: emerald
    display: '&eYour tokens offer is &6%AMOUNT%'
    theirdisplay: '&eTheir TokenManager tokens offer is &6%AMOUNT%'
    lore:
    - '&fClick to edit your offer!'
    - '&fYou have %BALANCE% tokens.'
    customModelData: 0
    increment: 1
    taxpercent: 0
    mode: chat
  beasttokens:
    enabled: true
    name: tokens
    material: emerald
    display: '&eYour tokens offer is &6%AMOUNT%'
    theirdisplay: '&eTheir TokenManager tokens offer is &6%AMOUNT%'
    lore:
    - '&fClick to edit your offer!'
    - '&fYou have %BALANCE% tokens.'
    customModelData: 0
    increment: 1
    taxpercent: 0
    mode: chat
  votingplugin:
    name: vote points
    enabled: false
    material: sunflower
    display: '&7Your vote points offer is &b%AMOUNT%'
    theirdisplay: '&7Their vote points offer is &b%AMOUNT%'
    lore:
    - '&fClick to edit your offer!'
    - '&fYou have %BALANCE% vote points.'
    taxpercent: 0
hooks:
  factions:
    allow-trades-in-enemy-territory: false
  worldguard:
    trading-flag: true
soundeffects:
  enabled: true
  onchange: true
  onaccept: true
  oncomplete: true
  oncountdown: true
debug-mode: false
configversion: 3.83
