#              _                               ___      __         _     _        #
#     /\      | |                             | \ \    / /        (_)   | |       #
#    /  \   __| |_   ____ _ _ __   ___ ___  __| |\ \  / /_ _ _ __  _ ___| |__     #
#   / /\ \ / _` \ \ / / _` | '_ \ / __/ _ \/ _` | \ \/ / _` | '_ \| / __| '_ \    #
#  / ____ \ (_| |\ V / (_| | | | | (_|  __/ (_| |  \  / (_| | | | | \__ \ | | |   #
# /_/    \_\__,_| \_/ \__,_|_| |_|\___\___|\__,_|   \/ \__,_|_| |_|_|___/_| |_|   #
# ##################################################################################
# Made by quantiom, config made for v1.2.3

# GitBook page: https://quantioms.gitbook.io/advancedvanish/

# Messages in this config use MiniMessage formatting
# For example, the message "&4Hello &a&lWorld" would need to be "<red>Hello <green><bold>World"
# Please check the documentation for more information: https://docs.adventure.kyori.net/minimessage/format.html

# Automatically check for updates
check-for-updates: true

# WARNING: The three following options will be IGNORED if cross-server-support is enabled

# Enable vanish on join
vanish-on-join: false
# Saves the vanish state when a player logs off
# Example: Player joins with `vanish-on-join` enabled, turns
# off vanish, and rejoins without vanish enabled
keep-vanish-state: true
# The option above must be set to true
# Stores vanish states to a file, so they
# persist outside of server restarts
keep-vanish-state-persistent: true

# Cross-server vanish synchronization
# Requires Redis or SQL
cross-server-support:
  enabled: true
  # Either "redis" or "sql"
  mode: redis
  redis:
    ip: 10.0.0.1
    port: 6379
    auth: t2wKkgkzYe5KeLZh26CLqVMjTs2s9QM5WncnPhcb8BwRrjVfmgnGVJ68T8JG2FEj
  sql:
    ip: 127.0.0.1
    port: 3306
    username: root
    password: ''
    database: minecraft
    table-prefix: advancedvanish_

# Actions when players are vanished
# true = enabled, false = disabled
when-vanished:
  join-messages: false
  leave-messages: false
  send-messages: true
  break-blocks: false
  place-blocks: false
  interact: false
  attack-entities: false
  receive-damage-from-entities: false
  open-and-use-chests: true
  pick-up-items: false
  drop-items: false
  # Find potion effect names here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
  # Write each effect in this format: "NAME:AMPLIFIER"
  # Example: "INVISIBILITY:2"
  give-potion-effects:
  - NIGHT_VISION:1
  lose-hunger: false
  mob-targeting: false
  fly:
    enable: true
    keep-on-unvanish: false # The "keep-fly-on-unvanish" permission will override this if the player has that permission

# Permissions
permissions:
  vanish: advancedvanish.vanish
  version-command: advancedvanish.version-command
  help-command: advancedvanish.help-command
  reload-config-command: advancedvanish.reload-config-command
  interact-command: advancedvanish.interact-command
  priority-command: advancedvanish.priority-command
  list-command: advancedvanish.list-command
  status-command: advancedvanish.status-command
  toggle-other-command: advancedvanish.toggle-other-command
  set-other-command: advancedvanish.set-other-command
  keep-fly-on-unvanish: advancedvanish.keep-fly
  join-vanished: advancedvanish.join-vanished

# Fake join/leave messages
join-leave-messages:
  fake-join-message-on-unvanish:
    enable: false
    # Placeholders:
    #   %priority% - The player's vanish priority
    message: <yellow>%player-name% has joined the game
  fake-leave-message-on-vanish:
    enable: false
    # Placeholders:
    #   %player-name% - The player's name
    message: <yellow>%player-name% has left the game.

# Hooks that will add support to other plugins
# Some hooks will not be enabled if the required plugin(s) are not found
hooks:
  # Hides players from Essentials commands such as: /list, /whois, etc...
  essentials: true
  # Requires ProtocolLib, removes vanished players from the server list (player count and players)
  server-list: false
  # Requires PlaceholderAPI, adds multiple placeholders which are configurable
  # in the placeholders section of this config
  placeholders: true
  # Shows a message above the hotbar if a player is vanished
  # The configurable message is in the messages section below.
  # Does NOT require or use ActionBarAPI
  actionbar: true
  # Requires DiscordSRV, sends a fake leave and join message when vanished/unvanished
  # and also requires the fake-join-message-on-unvanish / fake-leave-message-on-vanish to be
  # enabled (which is above)
  discordsrv: false
  # Requires Dynmap, will hide vanished players from the website
  dynmap: false
  # Requires squaremap, will hide vanished players from the website
  squaremap: true
  # Requires LibsDisguises, removes disguises when vanished
  libsdisguises: false
  # Requires PlayerParticles, removes active particles when vanished
  playerparticles: false

# Requires the "placeholders" hook to be enabled
placeholders:
  # The placeholder identifier
  identifier: advancedvanish
  
  # All of these placeholders will be in the format of
  # %<identifier>_<placeholder>%
  # Ex: %advancedvanish_is_vanished%
  is-vanished: is_vanished
  vanished-players: vanished_players
  player-count: player_count

# Vanish Priority - Requires a supported permissions plugin to function
#
# Allows players with higher priorities to see vanished players from
# lower priorities without the lower priority players being able to see
# them, but they will still all be in vanish.
#
# Supported permissions plugins:
#   - LuckPerms (recommended)
#   - bPermissions
#   - GroupManager
#
# To add the priority meta: (default is 0)
#   LuckPerms: /lp user/group <user|group> meta set meta.<meta-key> <priority-num>
#     (ex: /lp user quantiom meta set advancedvanish-priority 5)
#   bPermissions: (/user OR /group) meta <meta-key> <priority-num>
#     (ex: /user meta advancedvanish-priority 5)
#   GroupManager: Add the permission <meta-key>.<priority-num>, and AdvancedVanish will use the highest number
#     (ex: /manuaddp quantiom advancedvanish-priority.5)
#
priority:
  enable: true
  meta-key: advancedvanish-priority # will be meta.advancedvanish-priority.<num>

# Messages that are sent to players.
# Set any message here to "" to display nothing.
messages:
  # Set/enable a prefix used before all messages
  prefix:
    enabled: true
    value: '<#FB3850>🛡 <bold>Vanish </bold><dark_gray>➟ </dark_gray><white>'
  no-permission: <red>You do not have permission to execute this command.
  config-reloaded: Successfully reloaded the configuration.
  # Placeholders:
  #   %version% - The plugin version
  version-command: This server is running AdvancedVanish <red>%version%</red><white> by quantiom.
  vanish-on: You are now in vanish.
  vanish-off: You are no longer in vanish.
  cannot-chat-while-vanished: You cannot chat while you are in vanish.
  cannot-place-blocks-while-vanished: You cannot place blocks while you are in vanish.
  cannot-break-blocks-while-vanished: You cannot break blocks while you are in vanish.
  cannot-attack-entities-while-vanished: You cannot attack entities while you are in vanish.
  cannot-drop-items-while-vanished: You cannot drop items while you are in vanish.
  # Placeholders:
  #   %type% - The container type
  opening-container-silently: Opening %type% silently...
  # Placeholders:
  #   %priority% - The player's vanish priority
  vanish-priority: Your vanish priority is <red>%priority%</red><white>.
  not-using-vanish-priority: You are not using vanish priority, it can be enabled in the config.
  # Placeholders:
  #   %vanished-players% - A list of vanished players, or "None"
  vanished-list: 'Vanished players: <red>%vanished-players%'
  # Placeholders:
  #   %target-name% - The target's username
  #   %vanish-status% - "on" or "off"
  #   %vanish-status-word% - "vanished" or "not vanished"
  vanish-status-command: <red>%target-name%</red><white> is currently </white><red>%vanish-status-word%</red><white>.
  # Placeholders:
  #   %target-name% - The target's username
  #   %vanish-status% - "on" or "off"
  #   %vanish-status-word% - "vanished" or "not vanished"
  # This message is also used with the toggle command
  vanish-set-other-command: <white>Set </white><red>%target-name%'s</red><white> vanish to </white><red>%vanish-status%</red><white>.
  # Placeholders:
  #   %target-name% - The target's username
  #   %vanish-status% - "on" or "off"
  #   %vanish-status-word% - "vanished" or "not vanished"
  vanish-set-other-command-already: <red>%target-name%</red><white> is already </white><red>%vanish-status-word%
  must-be-vanished-to-use-command: <red>You must be vanished to use this command.
  # Placeholders:
  #   %interact-status%" - "on" or "off"
  vanish-interact-toggled: <white>You have turned %interact-status% interacting while vanished.
  action-bar: <#FB4C4C>🛡 <#FB6A6F>You are currently in vanish. <#FB4C4C>🛡
  disguise-removed-because-vanish: Your disguise has been <red>removed</red><white> because you are in vanish.

# Messages from the command handler
command-handler-messages:
  # Will use the prefix from the message section above before all of these messages
  use-prefix: true
  unknown-command: <red>Invalid arguments.
  # Placeholders:
  #   %command%
  #   %syntax%
  invalid-syntax: '<red>Usage: %command% %syntax%'
  error-performing-command: <red>There was an error performing this command.
  # Placeholders:
  #   %search% - The given player name
  could-not-find-player: <red>Couldn't find a player by the name of %search%.
  # Placeholders:
  #   %error% - The error message
  generic-error: '<red>Error: %error%'

# Config version - Do NOT change this manually
config-version: 10
