key_vote:
  Name: '&a&nVote Key'
  Description:
  - '&7Gives you key for the &aVote Crate&7.'
  Price: 25
  Purchase_Cooldown: 86400
  Priority: 10
  Inheritance:
    Rewards: []
    Price: []
  Preview:
    material: TRIPWIRE_HOOK
    amount: 1
    enchanted: true
    item-flags:
    - '*'
  Rewards:
    Commands:
    - '[CONSOLE] crate givekey %player% vote'
  Store:
    Slot: 11
    Page: 1

key_daily:
  Name: '&e&nDaily Key'
  Description:
  - '&7Gives you key for the &eDaily Crate&7.'
  Price: 10
  Purchase_Cooldown: 86400
  Priority: 10
  Inheritance:
    Rewards: []
    Price: []
  Preview:
    material: TRIPWIRE_HOOK
    amount: 1
    enchanted: true
    item-flags:
    - '*'
  Rewards:
    Commands:
    - '[CONSOLE] crate givekey %player% daily'
  Store:
    Slot: 13
    Page: 1

key_donor:
  Name: '&d&nDonor Key'
  Description:
  - '&7Gives you key for the &dDonor Crate&7.'
  Price: 5
  Purchase_Cooldown: 86400
  Priority: 10
  Inheritance:
    Rewards: []
    Price: []
  Preview:
    material: TRIPWIRE_HOOK
    amount: 1
    enchanted: true
    item-flags:
    - '*'
  Rewards:
    Commands:
    - '[CONSOLE] crate givekey %player% donor'
  Store:
    Slot: 15
    Page: 1
