#    _____        __ _       _ _                                                                            _
#   |_   _|      / _(_)     (_) |         /\                                                               | |
#     | |  _ __ | |_ _ _ __  _| |_ ___   /  \   _ __  _ __   ___  _   _ _ __   ___ ___ _ __ ___   ___ _ __ | |_ ___
#     | | | '_ \|  _| | '_ \| | __/ _ \ / /\ \ | '_ \| '_ \ / _ \| | | | '_ \ / __/ _ \ '_ ` _ \ / _ \ '_ \| __/ __|
#    _| |_| | | | | | | | | | | ||  __// ____ \| | | | | | | (_) | |_| | | | | (_|  __/ | | | | |  __/ | | | |_\__ \
#   |_____|_| |_|_| |_|_| |_|_|\__\___/_/    \_\_| |_|_| |_|\___/ \__,_|_| |_|\___\___|_| |_| |_|\___|_| |_|\__|___/
#
# InfiniteAnnouncements - config.yml - Main configuration
# Copyright 2020 Zach_FR | All Rights Reserved
#
#  Helpful Links:
#   Support |   https://discord.zachfr.com
#   Docs    |   https://docs.zachfr.com

announcement:
  # If enable it's will send one announcement at each interval set instead of use interval in announcement config.
  enable: true
  # Should messages be displayed in a random order?
  random: true
  # Interval of seconds between each announcement.
  interval: 80

system:
  # What locale should we use?
  locale: "en_US"