config_version: 1
bstats: true
update_checker: true
save_persistent_bars: true
WorldGuardRegion:
  Enabled: false
  Message: '&6<< &b%region% &6>>'
  Message2: '&b%region% &3<<>> &6and &c%number%&6 more.'
OnJoin:
  BossBar:
    Enabled: true
    Message: '&6&lLIMITED SALE &7- &c&l15% OFF EVERYTHING &7(do /buy)'
    Color: blue
    Time: 20
    Style: ''
    Health: 1
  Title:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6'
    SubTitle: '&bto the best server ever!'
    fadein: 5
    fadeout: 5
    time: 20
  ActionBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
OnDeath:
  BossBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
    Color: green
    Time: 10
    Style: '6'
    Health: 1
  Title:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6'
    SubTitle: '&bto the best server ever!'
    fadein: 5
    fadeout: 5
    time: 20
  ActionBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
OnCommand:
  list:
  - examplecmd
  examplecmd:
    BossBar:
      Message: '&6You ran a command!'
      Color: green
      Time: 10
      Style: '6'
      Health: 1
    ActionBar:
      Message: '&6ActionBars can be used&6!'
    Title:
      Message: '&6Along with titles.&6'
      SubTitle: '&bThese support placeholderapi!'
      fadein: 5
      fadeout: 5
      time: 20
BossBarMessages:
  Enabled: false
  World_Whitelist_Enabled: false
  Random_Order: false
  No_Progress: false
  World_Whitelist:
  - world
  Messages:
    Message1:
      Message: '&1BossBar #1'
      Color: green
      Style: '6'
      Time: 10
    Message2:
      Message: '&2BossBar #2'
      Color: blue
      Style: '6'
      Time: 10
    Message3:
      Message: '&3BossBar #3'
      Color: red
      Style: '6'
      Time: 10
Title_Announcements:
  Enabled: false
  Random_Order: false
  Number_Of_Messages: 3
  Time: 20
  '1':
    Message: '&6Message 1&6'
    SubTitle: '&bMeassage 1'
    fadein: 5
    fadeout: 5
    time: 20
  '2':
    Message: '&6Message 2&6'
    SubTitle: '&bMessage 2'
    fadein: 5
    fadeout: 5
    time: 20
  '3':
    Message: '&6Message 3&6'
    SubTitle: '&bMessage 3'
    fadein: 5
    fadeout: 5
    time: 20
Action_Announcements:
  Enabled: false
  Random_Order: false
  Number_Of_Messages: 3
  Time: 10
  '1':
    Message: Message 1
  '2':
    Message: Message 2
  '3':
    Message: Message 3
