# Please visit https://github.com/froobynooby/FarmControl/wiki/Profiles for help with making profiles.

profiles:
  # Remove random movements and disable collisions of mobs in animal farms
  soft-nerf-animal-farms:
    group:
      types:
        - "category:animal"
      count: 15
      distance: 5
    actions:
      - remove-random-movement
      - disable-collisions

  # Remove the awareness of mobs in animal farms
  hard-nerf-animal-farms:
    group:
      types:
        - "category:animal"
      count: 15
      distance: 5
    actions:
      - remove-awareness
      - disable-collisions

  # Remove the AI of mobs in animal farms
  freeze-animal-farms:
    group:
      types:
        - "category:animal"
      count: 15
      distance: 5
    actions:
      - remove-ai
      - disable-collisions

  # No more than 20 animals (all of the same type) within close proximity
  trim-animal-farms:
    group:
      types:
        - "category:animal"
      count: 21
      distance: 5
      pure: true
    actions:
      - kill

  # No more than 50 animals (all of the same type) sparsely placed (within 160 blocks of each other)
  trim-sparse-animal-farms:
    group:
      types:
        - "category:animal"
      count: 51
      distance: 160
      pure: true
    actions:
      - kill

  # No more than 10 villagers per chunk
  trim-villager-chunks:
    group:
      types:
        - "villager"
      count: 9
      distance: same-chunk
    actions:
      - kill
  villager-nerf:
    group:
      types:
        - "villager"
      count: 2
      distance: same-chunk
    actions:
      #- remove-random-movement
      #- remove-awareness
      #- disable-collisions